### PR TITLE
* First commit | Mini project 1

### PR DESCRIPTION
**Pull request by AroLalayan**
First commit

### CODE REVIEW

**Comment by AroLalayan** [comment]
First commit JS mini-project 1

**Comment by Robert-Ayvazyan** [comment]
when does the sentence end with ? , the count of sentences does not increase

**Comment by AroLalayan** [comment]
Խնդիրը ուղղել եմ,
էստեղ poll request-ի լինկն է, կարող եք նայել

https://github.com/AroLalayan/word-counter-arayik-lalayan/pull/2

նաև merge եմ արել master-ի վրա

**Comment by Robert-Ayvazyan** [comment]
Good, Success

**Comment by lusinegalstyan1** [comment]
The overall design — Do the interactions of various pieces of code make sense?
Functionality — Does it do what the developer intended?
Complexity — Is it more complex than it should be?
Naming — Did the developer pick good names for everything?
Good Things
------------------------------------------------------------------------------------------------------------------------
The background colors are working. 
I tested this 2-paragraph text: "barev, test. barev, test. barev, test.
6 words."

Count of letters: 47 letters: incorrect
Count of sentences: 3 sentences: incorrect
Count of words: 7 words: correct
Count of numbers 0: the developer didn't count the numbers

The developer counted paragraphs, but when I tasted a 2-paragraph text (I used "return"
 button to create the 2nd paragraph), it didn't work, it counted  "o paragraph" .
So, paragraph counting: incorrect

The overall design —  good,
Functionality — It doesn't do what the developer intended, besides Count of words.
Complexity — It's good.
Naming — The developer picked good names.

**Pull request merged**
